-- Schema per test con H2 in modalità PostgreSQL
CREATE TABLE IF NOT EXISTS connettori (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_connettore VARCHAR(255) NOT NULL,
    cod_proprieta VARCHAR(255) NOT NULL,
    valore VARCHAR(255) NOT NULL,
    CONSTRAINT uk_connettori UNIQUE (cod_connettore, cod_proprieta)
);

CREATE TABLE IF NOT EXISTS configurazione (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    valore CLOB,
    CONSTRAINT uk_configurazione_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS intermediari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_intermediario VARCHAR(255) NOT NULL,
    cod_connettore_pdd VARCHAR(255),
    cod_connettore_recupero_rt VARCHAR(255),
    cod_connettore_aca VARCHAR(255),
    cod_connettore_gpd VARCHAR(255),
    cod_connettore_fr VARCHAR(255),
    cod_connettore_backoffice_ec VARCHAR(255),
    cod_connettore_ftp VARCHAR(255),
    denominazione VARCHAR(255),
    principal VARCHAR(255),
    principal_originale VARCHAR(255),
    abilitato BOOLEAN NOT NULL,
    CONSTRAINT uk_intermediari_cod UNIQUE (cod_intermediario)
);

CREATE TABLE IF NOT EXISTS stazioni (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_stazione VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    abilitato BOOLEAN NOT NULL,
    application_code INTEGER,
    versione VARCHAR(255),
    id_intermediario BIGINT NOT NULL,
    CONSTRAINT uk_stazioni_cod UNIQUE (cod_stazione),
    CONSTRAINT fk_stazioni_intermediario FOREIGN KEY (id_intermediario) REFERENCES intermediari(id)
);

CREATE TABLE IF NOT EXISTS domini (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_dominio VARCHAR(35) NOT NULL,
    gln VARCHAR(35),
    abilitato BOOLEAN NOT NULL,
    ragione_sociale VARCHAR(70) NOT NULL,
    aux_digit INT NOT NULL DEFAULT 0,
    iuv_prefix VARCHAR(255),
    segregation_code INT,
    logo BINARY LARGE OBJECT,
    cbill VARCHAR(255),
    aut_stampa_poste VARCHAR(255),
    cod_connettore_my_pivot VARCHAR(255),
    cod_connettore_secim VARCHAR(255),
    cod_connettore_gov_pay VARCHAR(255),
    cod_connettore_hyper_sic_apk VARCHAR(255),
    intermediato BOOLEAN NOT NULL,
    tassonomia_pago_pa VARCHAR(35),
    scarica_fr BOOLEAN NOT NULL,
    id_stazione BIGINT,
    id_applicazione_default BIGINT,
    CONSTRAINT uk_domini_cod UNIQUE (cod_dominio),
    CONSTRAINT fk_domini_stazione FOREIGN KEY (id_stazione) REFERENCES stazioni(id)
);
