-- Schema per test con H2 in modalità PostgreSQL
CREATE TABLE IF NOT EXISTS connettori (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_connettore VARCHAR(255) NOT NULL,
    cod_proprieta VARCHAR(255) NOT NULL,
    valore VARCHAR(255) NOT NULL,
    CONSTRAINT uk_connettori UNIQUE (cod_connettore, cod_proprieta)
);

CREATE TABLE IF NOT EXISTS configurazione (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    valore CLOB,
    CONSTRAINT uk_configurazione_nome UNIQUE (nome)
);
